name: weathers_app
description: "A weather app with API integration and Firebase"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  
  # HTTP requests for API calls
  http: ^1.2.0
  
  # Firebase - latest stable versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  
  # State management
  provider: ^6.1.2
  
  # Location services
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # UI components
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.3.3

  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.0
  # Optionally, for ML: tflite, google_ml_kit, or similar

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
  