name: weathers_app
description: "A weather app with API integration and Firebase"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  
  # HTTP requests for API calls
  http: ^1.2.0
  
  # Firebase - latest stable versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  
  # State management
  provider: ^6.1.2
  
  # Location services
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # UI components
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.3.3

  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.0
  # Optionally, for ML: tflite, google_ml_kit, or similar

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#6B46C1"
    theme_color: "#6B46C1"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
  